version: "3"

vars:
  FRONTEND_DIR: frontend
  FRONTEND_DIST: "{{.FRONTEND_DIR}}/dist"
  VERSION: "{{.GIT_TAG}}"

tasks:
  default:
    cmds:
      - task dev

  clean:
    desc: Cleans env for local development/CI
    cmds:
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "try { Remove-Item -Recurse -Force -LiteralPath 'build/bin','frontend/node_modules' -ErrorAction Stop } catch { } ; exit 0"
        {{else}}
        rm -rf build/bin
        rm -rf frontend/node_modules
        {{end}}

  ensure-dist:
    desc: Ensure frontend/dist/.gitkeep exists
    silent: true
    cmds:
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path '{{.FRONTEND_DIST}}' | Out-Null; New-Item -ItemType File -Force -Path '{{.FRONTEND_DIST}}/.gitkeep' | Out-Null"
        {{else}}
        mkdir -p "{{.FRONTEND_DIST}}"
        : > "{{.FRONTEND_DIST}}/.gitkeep"
        {{end}}

  

  dev:
    desc: Start Wails dev server
    cmds:
      - |
        {{if eq OS "windows"}}
        task wails-dev-win
        {{else}}
        task wails-run ACTION=dev
        {{end}}

  build:
    desc: Production build
    deps:
      - ensure-dist
    cmds:
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "try { Remove-Item -Recurse -Force -LiteralPath 'build/bin','frontend/node_modules' -ErrorAction Stop } catch { } ; exit 0"
        {{else}}
        rm -rf build/bin
        {{end}}
      - |
        {{if eq OS "windows"}}
        task wails-build-win
        {{else}}
        task wails-run ACTION=build
        {{end}}

  test:
    desc: Run Go tests
    deps:
      - ensure-dist
    cmds:
      - go test ./... -count=1 -coverprofile=cover.out

  lint:
    desc: Go vet + golangci-lint + optional frontend lint
    cmds:
      - go vet ./...
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "if (Get-Command golangci-lint -ErrorAction SilentlyContinue) { golangci-lint run } else { Write-Host 'skipping: golangci-lint not installed' }"
        {{else}}
        bash -lc 'command -v golangci-lint >/dev/null && golangci-lint run || echo "skipping: golangci-lint not installed"'
        {{end}}
      - |
        cd frontend
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "if (Test-Path 'package.json') { npm run -s lint --if-present } else { Write-Host 'no frontend dir' }"
        {{else}}
        bash -lc 'if [ -f "package.json" ] && npm -s run | grep -q "^  lint"; then npm run -s lint; else echo "frontend: no lint script"; fi'
        {{end}}

  fmt:
    desc: Format Go + frontend
    cmds:
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "if (Get-Command gofumpt -ErrorAction SilentlyContinue) { gofumpt -w . } else { gofmt -s -w . }"
        {{else}}
        bash -lc 'command -v gofumpt >/dev/null && gofumpt -w . || gofmt -s -w .'
        {{end}}
      - |
        cd frontend
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "if (Test-Path 'package.json') { if (npm -s run | Select-String '^  fmt') { npm run -s fmt } else { npx -y prettier@latest --log-level warn --write '**/*.{ts,tsx,js,jsx,css,scss,html,json,md}' } }"
        {{else}}
        bash -lc 'if [ -f "package.json" ] && npm -s run | grep -q "^  fmt"; then npm run -s fmt; else npx -y prettier@latest --log-level warn --write "**/*.{ts,tsx,js,jsx,css,scss,html,json,md}"; fi'
        {{end}}

  # ------------------------------------------------------------
  # Shared Wails runner for linux/darwin (computes tags + CGO once)
  # Call with: task wails-run ACTION=dev
  #            task wails-run ACTION=build
  # ------------------------------------------------------------
  wails-run:
    desc: Run Wails with computed tags (linux/darwin)
    deps:
      - ensure-dist
    platforms: [linux, darwin]
    vars:
      ACTION: '{{.ACTION | default "dev"}}'
      CGO_ENABLED:
        sh: |
          echo 1
      WAILS_TAGS:
        sh: |
          set -euo pipefail
          # Only Linux uses x11/webkit tags in your scheme
          if [ "{{OS}}" != "linux" ]; then
            echo ""
            exit 0
          fi

          tags=""

          # X11 tag only when actually under X11
          if [ "${XDG_SESSION_TYPE:-}" = "x11" ]; then
            tags="x11"
          fi

          # WebKitGTK tag based on installed pkg-config module
          if command -v pkg-config >/dev/null 2>&1; then
            if pkg-config --exists webkit2gtk-4.1; then
              if [ -n "$tags" ]; then tags="$tags,webkit2_41"; else tags="webkit2_41"; fi
            elif pkg-config --exists webkit2gtk-4.0; then
              if [ -n "$tags" ]; then tags="$tags,webkit2_40"; else tags="webkit2_40"; fi
            fi
          fi

          echo "$tags"
      WAILS_TAG_ARGS:
        sh: |
          set -euo pipefail
          tags='{{.WAILS_TAGS}}'
          if [ -n "$tags" ]; then
            echo "-tags=$tags"
          else
            echo ""
          fi
    cmds:
      - |
        set -euo pipefail
        echo "ACTION={{.ACTION}}"
        echo "CGO_ENABLED={{.CGO_ENABLED}}"
        echo "WAILS_TAGS={{.WAILS_TAGS}}"
        if [ "{{.ACTION}}" = "dev" ]; then
          CGO_ENABLED={{.CGO_ENABLED}} wails dev {{.WAILS_TAG_ARGS}}
        else
          CGO_ENABLED={{.CGO_ENABLED}} wails build -clean {{.WAILS_TAG_ARGS}}
        fi

  wails-dev-win:
    desc: Run wails dev (windows)
    deps:
      - ensure-dist
    platforms: [windows]
    cmds:
      - wails dev

  wails-build-win:
    desc: Run wails build (windows)
    deps:
      - ensure-dist
    platforms: [windows]
    cmds:
      - wails build -clean