// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFactProviders() {
  return window["go"]["main"]["App"]["GetFactProviders"]();
}

export function OpenFactProviderFolder() {
  return window["go"]["main"]["App"]["OpenFactProviderFolder"]();
}

export function SetReadPlan(arg1) {
  return window["go"]["main"]["App"]["SetReadPlan"](arg1);
}

export function StartEmulatorClient() {
  return window["go"]["main"]["App"]["StartEmulatorClient"]();
}
