// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { repo } from "../models";

export function GetFactProviders(): Promise<Array<repo.Provider>>;

export function OpenFactProviderFolder(): Promise<void>;

export function SetReadPlan(arg1: string): Promise<void>;

export function StartEmulatorClient(): Promise<void>;
